import Link from 'next/link';
import './globals.css';
import { Control } from './Control';

export const metadata = {
  title: 'ALPACA',
  description: 'Generated by JWL',
};

export default async function RootLayout({ children }) {
  const resp = await fetch('http://localhost:9999/topics', {
    cache: 'no-store',
  }); //한번 실행하면.next에 캐쉬저장
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
          {/* <li>
            <Link href="/read/1">html</Link>
          </li>
          <li>
            <Link href="/read/2">css</Link>
          </li> */}
        </ol>
        {children}
        <Control></Control>
      </body>
    </html>
  );
}
